#include "RuntimeBuilder.h"

using namespace llvm;

namespace angara {

void RuntimeBuilder::generateMemoryManagement() {
    // ARC is fully removed. Memory management is handled by the GC.
    // The GC functions (__ang_gc_alloc, __ang_gc_mark, __ang_gc_sweep, etc.)
    // are generated by the MarkSweepGC in generateFunctions().
    // No incref, decref, or free_object functions are needed.
}

} // namespace angara
