#pragma once

#include "ConfigParser.h"
#include "CompilerDriver.h"
#include <string>
#include <vector>
#include <set>
#include <map>
#include <chrono>

namespace angara {

    /// Orchestrates the full build pipeline: parsing, native module compilation,
    /// Angara source compilation via LLVM, linking, and publish.
    class BuildSystem {
    public:
        BuildSystem();

        /// Parses the spec file and builds all projects in the workspace.
        /// @param spec_file  Path to the .abs build specification file.
        /// @return True if all projects built successfully.
        bool build(const std::string& spec_file);

        /// Removes the .angara/build directory for the given workspace.
        /// @param spec_file  Path to the .abs build specification file.
        /// @return True if clean succeeded.
        bool clean(const std::string& spec_file);

        /// Builds the workspace and then executes the first app project.
        /// @param spec_file  Path to the .abs build specification file.
        /// @return True if the app ran and exited with code 0.
        bool run(const std::string& spec_file);

        /// Builds the workspace and copies all artifacts to an output directory.
        /// @param spec_file   Path to the .abs build specification file.
        /// @param output_dir  Destination directory. Defaults to .angara/publish.
        /// @return True if at least one artifact was published.
        bool publish(const std::string& spec_file, const std::string& output_dir = "");

        /// Sets the LLVM target triple for cross-compilation.
        void set_target(const std::string& triple) { m_target_triple = triple; }

        /// Sets the sysroot path for cross-compilation.
        void set_sysroot(const std::string& path) { m_sysroot = path; }

        /// Sets the build mode (debug or release).
        void set_build_mode(BuildMode mode) { m_build_mode = mode; }

        /// TOOL-2: sets the number of parallel compilation threads.
        void set_jobs(int n) { m_jobs = n; }

        /// TOOL-2: forces a full rebuild, ignoring the incremental cache.
        void set_force_rebuild(bool v) { m_force_rebuild = v; }

    private:
        const std::string m_angara_home = "/opt/angara";
        const std::string m_native_lib_path;
        const std::string m_std_lib_path;

        std::string m_workspace_root;
        std::string m_build_dir;
        std::map<std::string, std::string> m_project_dirs;
        std::string m_target_triple;
        std::string m_sysroot;
        BuildMode m_build_mode = BuildMode::DEBUG;

        // TOOL-2: parallel + incremental compilation flags.
        int m_jobs = 0;
        bool m_force_rebuild = false;

        std::vector<std::string> m_built_artifacts;

        /// Compiles a single project: pre-build, native modules, Angara source, linking, post-build.
        /// @param config          The project configuration.
        /// @param project_entries Map of project names to their absolute entry file paths.
        /// @return True if the project built successfully.
        bool build_project(const ProjectConfig& config,
                           const std::map<std::string, std::string>& project_entries);

        /// Compiles all native C/C++ modules declared in a project.
        /// @param config       The project configuration containing native module declarations.
        /// @param project_root Absolute path to the project directory.
        /// @return True if all native modules compiled successfully.
        bool build_native_modules(const ProjectConfig& config,
                                  const std::string& project_root);

        /// Compiles a single native C/C++ module into a shared library.
        /// @param mod          The native module configuration.
        /// @param project_root Absolute path to the project directory.
        /// @return True if the module compiled and linked successfully.
        bool compile_native_module(const NativeModuleConfig& mod,
                                   const std::string& project_root);

        /// Executes a pre/post-build shell command step.
        /// @param step   The build step to execute.
        /// @param label  Display label (e.g. "pre-build").
        /// @return True if the command succeeded or was empty.
        bool execute_build_step(const BuildStep& step, const std::string& label);

        /// Links compiled object files and libraries into the final binary or shared library.
        /// @param config          The project configuration.
        /// @param object_files    Object files generated by the LLVM backend.
        /// @param discovered_libs Libraries discovered during compilation.
        /// @param project_root    Absolute path to the project directory.
        /// @return True if linking succeeded.
        bool link_artifacts(const ProjectConfig& config,
                            const std::set<std::string>& object_files,
                            const std::vector<std::string>& discovered_libs,
                            const std::string& project_root) const;

        /// Resolves the optimization flags string from the build profile.
        /// @param profile  The build profile.
        /// @return A flag string like "-O2".
        std::string resolve_opt_flags(const BuildProfile& profile) const;

        /// Resolves the output directory for a project's build artifacts.
        /// @param config  The project configuration.
        /// @return Absolute path to the output directory.
        std::string resolve_output_dir(const ProjectConfig& config) const;

        /// Returns the output path for a compiled native module shared library.
        /// @param module_name  The module's name.
        /// @return Absolute path with the platform-appropriate extension.
        std::string get_module_output_path(const std::string& module_name) const;

        /// Prints a summary of all built artifacts with file sizes.
        void print_build_summary() const;

        /// Prints a decorative message after publishing.
        void print_publish_easter_egg() const;

        /// Formats a byte count as a human-readable string (e.g. "1.2 MB").
        /// @param bytes  The file size in bytes.
        /// @return A formatted string.
        static std::string format_file_size(std::uintmax_t bytes);
    };
}
